# -*- coding: utf-8 -*-
"""RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cxMKp6zMDjRcB_31q6-NFZrkXNStkJDO
"""

!pip install langchain \
langchain_community \
langchain_huggingface \
faiss-cpu \
langchain_core \
fastapi \
pydantic \
typing \
pypdf

import os
from langchain_community.document_loaders import PyPDFLoader, DirectoryLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_huggingface import HuggingFaceEndpoint
from langchain_core.prompts import PromptTemplate
from langchain.chains import RetrievalQA
from pydantic import BaseModel
from typing import List

from huggingface_hub import login

# Replace with your Hugging Face token
HF_TOKEN = os.environ.get("HF_API_TOKEN")

# Log in
login(HF_TOKEN)

DATA_PATH = "/content/"
DB_FAISS_PATH = "vectorstore/db_faiss"

# Step 1: Load raw PDF(s)
def load_pdf_files(data):
    loader = DirectoryLoader(data, glob='*.pdf', loader_cls=PyPDFLoader)
    return loader.load()

# Step 2: Create Chunks
def create_chunks(extracted_data):
    text_splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50)
    return text_splitter.split_documents(extracted_data)

# Step 3: Create Vector Embeddings
def get_embedding_model():
    return HuggingFaceEmbeddings(model_name="mixedbread-ai/mxbai-embed-large-v1")

# Step 4: Store embeddings in FAISS
def create_vector_db(documents):
    text_chunks = create_chunks(documents)
    embedding_model = get_embedding_model()
    db = FAISS.from_documents(text_chunks, embedding_model)
    db.save_local(DB_FAISS_PATH)
    return db

# Load and create the VectorDB
documents = load_pdf_files(DATA_PATH)
vector_db = create_vector_db(documents)

# Define the Pydantic model for the response data structure
class QueryResponse(BaseModel):
    result: str
    source_documents: List[str]

# If you want to define more validation, you can add models for requests as well
class QueryRequest(BaseModel):
    query: str

HUGGINGFACE_REPO_ID = "mistralai/Mistral-7B-Instruct-v0.3"

# Load the LLM (HuggingFace model)
def load_llm(huggingface_repo_id):
    llm = HuggingFaceEndpoint(
        repo_id=huggingface_repo_id,
        task="text-generation",
        temperature=0.5,
        model_kwargs={"token": HF_TOKEN, "max_length": "512"}
    )
    return llm

# Custom Prompt Template for the agent
CUSTOM_PROMPT_TEMPLATE = """
Use the pieces of information provided in the context to answer user's question.
If you don't know the answer, just say that you don't know, don't try to make up an answer.
Don't provide anything out of the given context

Context: {context}
Question: {question}

Start the answer directly. No small talk please.
"""

# Set up the custom prompt
def set_custom_prompt(custom_prompt_template):
    return PromptTemplate(template=custom_prompt_template, input_variables=["context", "question"])

# Create QA chain
def create_qa_chain():
    llm = load_llm(HUGGINGFACE_REPO_ID)
    prompt = set_custom_prompt(CUSTOM_PROMPT_TEMPLATE)
    return RetrievalQA.from_chain_type(
        llm=llm,
        chain_type="stuff",
        retriever=vector_db.as_retriever(search_kwargs={'k': 3}),
        return_source_documents=True,
        chain_type_kwargs={'prompt': prompt}
    )

# Invoke the agent with a query
def query_agent(query):
    qa_chain = create_qa_chain()
    response = qa_chain.invoke({'query': query})
    return response

query = "What is a network?"

# Call the query_agent function
response = query_agent(query)

# Print the response
print(response['query'])
print(response['result'])